FirstNavSave
coquito143/tartine pull request #7
Opened 2019-11-16 18:18 UTC by y0ursj

finished styling some of the NAV....still need to work on it more

2019-11-16 22:28 UTC, coquito143 requested changes
please make the reference to a { } more specific.  The following definition will impact all <a href> elements in our file which is not the intention.  

a {
  margin-right: 50px;
  margin-left: 50px;
}

can we change to this instead?
.topnav a {
  margin-right: 50px;
  margin-left: 50px;
}

2019-11-16 22:34 UTC, y0ursj commented
Yes I agree to the changes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: coquito143 <notifications@github.com>
Sent: Saturday, November 16, 2019 5:28:57 PM
To: coquito143/tartine <tartine@noreply.github.com>
Cc: Sujith John <y0ursj@hotmail.com>; Author <author@noreply.github.com>
Subject: Re: [coquito143/tartine] FirstNavSave (#7)


@coquito143 requested changes on this pull request.

please make the reference to a { } more specific. The following definition will impact all elements in our file which is not the intention.

a {
margin-right: 50px;
margin-left: 50px;
}

can we change to this instead?
.topnav a {
margin-right: 50px;
margin-left: 50px;
}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coquito143/tartine/pull/7?email_source=notifications&email_token=AGEAFNTBSNWOZQM5NNAQM3LQUBX2TA5CNFSM4JOGJF32YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCL2CXTQ#pullrequestreview-317991886>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AGEAFNWQZID3YPXGKF5U7MTQUBX2TANCNFSM4JOGJF3Q>.

2019-11-17 02:37 UTC, lemondsun approved these changes

2019-11-17 04:17 UTC, lemondsun approved these changes

2019-11-18 00:43 UTC, coquito143 approved these changes

2019-11-18 00:43 UTC, merged